class_name Enums

enum EntityType { CHARACTER, MOVE, VERDICT, INVENTORY, ITEM, WEAPON, ARMOR, LOCATION, CHARACTER_MODEL, LOCATION_MODELS, SAVE_DATA }
enum States { BOOT, TITLE, MAIN_MENU, EXPLORING, EXPLORING_MENU, BATTLE, INVENTORY, EQUIPMENT }

enum DiceType { NONE = 0, D4 = 4, D6 = 6, D8 = 8, D10 = 10, D12 = 12, D20 = 20, D100 = 100 }
enum DiceOutcome { WORST, WITH_CONSEQUENCE, BEST }
enum DiceRollType { NONE, WORST, NORMAL, BEST }

# used to set character class stats
enum CharacterAbility { NONE, CONSTITUTION, STRENGTH, DEXTERITY }
enum CharacterModifier { NONE, CON, STR, DEX }

enum CharacterType { PC, NPC, FOE }

enum MoveType { SKILL, ITEM }
enum MoveTargetType { NONE, ANY, FRIENDLY, FOE, ANY_ALL, FRIENDLY_ALL, FOE_ALL }
enum MoveModifierProperty { NONE, ATK_P, DEF_P, CD_P, ATK_M, DEF_M, CD_M }
enum MoveModifierType { ATK, DEF, CD }

enum ItemType { CONSUMABLE, KEY }

enum RoomType { DUMMY, _0_EXIT, _1_EXIT, _2_EXITS_I, _2_EXITS_L, _3_EXITS, _4_EXITS }

enum Direction { NORTH, EAST, SOUTH, WEST, UP, DOWN, FORWARD, BACKWARD, LEFT, RIGHT, NONE }

enum CameraOffsetDirection { FOWARD = -1, BACKWARD = 1 }
enum CameraOffsetRotation { RIGHT = -1, LEFT = 1 }

enum AfflictionType { TODO }

enum MessageType { AUTO_TOP, AUTO_BOTTOM, DIALOG }

enum GuiAction { NEW_WINDOW, CONFIRM, CANCEL, SLIDE, PREVIOUS, NEXT, TOGGLE }
enum GuiWindowType { FOREGROUND, BACKGROUND, PERMANENT }

enum Fact {
	ANY,
	
	HP_HIGHEST, HP_LOWEST,
	
	HP_GREATER_95, HP_GREATER_75, HP_GREATER_50, HP_GREATER_35, HP_GREATER_15, HP_GREATER_5,
	HP_LOWER_95, HP_LOWER_75, HP_LOWER_50, HP_LOWER_35, HP_LOWER_15, HP_LOWER_5,
	
	MOD_3_ATK, MOD_GT_2_ATK, MOD_GT_1_ATK,
	MOD_LT_0_ATK, MOD_LT_M1_ATK, MOD_LT_M2_ATK, MOD_M3_ATK,
	
	MOD_3_DEF, MOD_GT_2_DEF, MOD_GT_1_DEF,
	MOD_LT_0_DEF, MOD_LT_M1_DEF, MOD_LT_M2_DEF, MOD_M3_DEF,
	
	MOD_3_CD, MOD_GT_2_CD, MOD_GT_1_CD,
	MOD_LT_0_CD, MOD_LT_M1_CD, MOD_LT_M2_CD, MOD_M3_CD
}

